CREATE DATABASE IF NOT EXISTS pedidos_db;
USE pedidos_db;

CREATE TABLE IF NOT EXISTS pedidos (
    id BIGINT PRIMARY KEY,
    estado VARCHAR(50) NOT NULL,
    alimentos JSON NOT NULL,
    total DECIMAL(10,2) DEFAULT 0,
    fecha_creacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    fecha_actualizacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
